# vim: ft=yaml
---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: mattermost
  state_top:
    base:
      "*":
        - mattermost
  pillars:
    top.sls:
      base:
        "*":
          - mattermost

platforms:
  - name: bento/debian-8.8

suites:
  - name: default
    provisioner:
      pillars:
        mattermost.sls:
          mattermost:
            enabled: true
            mockup: true

  - name: custom
    provisioner:
      pillars-from-files:
        mattermost.sls: pillar-custom.sls
