# vim: ft=yaml
---
driver:
  name: docker
  image: debian:8

provisioner:
  name: salt_solo
  formula: mattermost
  state_top:
    base:
      "*":
        - mattermost
  pillars:
    top.sls:
      base:
        "*":
          - mattermost

platforms:
  - name: debian

suites:
  - name: default
    provisioner:
      pillars:
        mattermost.sls:
          mattermost:
            enabled: true
            mockup: true

  - name: custom
    provisioner:
      pillars-from-files:
        mattermost.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - mattermost
